apiVersion: apps/v1
kind: Deployment
metadata:
  name: authenticat-app-deployement-02
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: authenticat-app-container-02
        image: othnielparfait/yoptestauthenticat-02:latest
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: authenticate-app-service-02
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer