apiVersion: apps/v1
kind: Deployment
metadata:
  name: authenticat-app-deployement-02
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: authenticat-app-container-02
        image: othnielparfait/yoptestauthenticat-02:latest
        ports:
        - containerPort: 8000